#pragma once

#include "types.hpp"
#include <cstdint>
#include <string>
#include <chrono>

namespace hft {

/// Represents an order in the order book
struct Order {
    uint64_t orderId;           // Unique order identifier
    uint64_t timestampNs;       // Nanoseconds since epoch
    Side side;                  // BUY or SELL
    OrderType type;             // LIMIT, MARKET, IOC, FOK
    double price;               // Limit price (0 for market orders)
    uint32_t quantity;          // Original quantity
    uint32_t filledQty;         // Quantity already filled
    std::string traderId;       // Trader/participant identifier

    /// Get remaining quantity
    [[nodiscard]] uint32_t remainingQty() const {
        return quantity - filledQty;
    }

    /// Check if order is fully filled
    [[nodiscard]] bool isFilled() const {
        return filledQty >= quantity;
    }

    /// Create a new order with current timestamp
    static Order create(
        uint64_t orderId,
        Side side,
        OrderType type,
        double price,
        uint32_t quantity,
        const std::string& traderId = ""
    ) {
        auto now = std::chrono::high_resolution_clock::now();
        auto ns = std::chrono::duration_cast<std::chrono::nanoseconds>(
            now.time_since_epoch()
        ).count();

        return Order{
            orderId,
            static_cast<uint64_t>(ns),
            side,
            type,
            price,
            quantity,
            0,
            traderId
        };
    }
};

/// Execution report generated by matching engine
struct ExecutionReport {
    uint64_t orderId;           // Original order ID
    uint64_t execId;            // Unique execution ID
    ExecType type;              // NEW, FILLED, PARTIAL_FILL, etc.
    double execPrice;           // Execution price
    uint32_t execQty;           // Executed quantity
    uint64_t timestampNs;       // Execution timestamp
    std::string traderId;       // Trader who owns this order

    /// Create an execution report with current timestamp
    static ExecutionReport create(
        uint64_t orderId,
        uint64_t execId,
        ExecType type,
        double price = 0.0,
        uint32_t qty = 0,
        const std::string& traderId = ""
    ) {
        auto now = std::chrono::high_resolution_clock::now();
        auto ns = std::chrono::duration_cast<std::chrono::nanoseconds>(
            now.time_since_epoch()
        ).count();

        return ExecutionReport{
            orderId,
            execId,
            type,
            price,
            qty,
            static_cast<uint64_t>(ns),
            traderId
        };
    }
};

} // namespace hft
